CUSTOM_TABLE_FIELDS_ON_URL = """&c=0,1,2,3,4,5,6,7,8,9,10,11,13,75,14,15,16,
77,17,18,19,21,23,22,82,78,127,128,24,25,85,26,27,28,29,30,31,84,32,33,34,37,
38,40,41,43,44,46,47,48,49,50,51,57,58,59,68,76,62,63,64,67,65,66,120"""

CUSTOM_TABLE_ALL_FIELDS = [
    'Ticker',
    'Company',
    'Sector',
    'Industry',
    'Country',
    'Market Cap',
    'P/E',
    'Fwd P/E',
    'PEG',
    'P/S',
    'P/B',
    'P/FCF',
    'Dividend',
    'Payout Ratio',
    'EPS',
    'EPS next Q',
    'EPS this Y',
    'EPS next Y',
    'EPS past 5Y',
    'Sales past 5Y',
    'Sales Q/Q',
    'EPS Q/Q',
    'Sales',
    'Income',
    'EPS Surprise',
    'Revenue Surprise',
    'Outstanding',
    'Float',
    'Float %',
    'Insider Own',
    'Insider Trans',
    'Inst Own',
    'Inst Trans',
    'Float Short',
    'Short Ratio',
    'Short Interest',
    'ROA',
    'ROE',
    'ROI',
    'LTDebt/Eq',
    'Debt/Eq',
    'Oper M',
    'Profit M',
    'Perf Month',
    'Perf Quart',
    'Perf Year',
    'Perf YTD',
    'Beta',
    'ATR',
    'Volatility M',
    'Volatility W',
    '52W High',
    '52W Low',
    'RSI',
    'Earnings',
    'Employees',
    'Recom',
    'Avg Volume',
    'Rel Volume',
    'Volume',
    'Price',
    'Change',
    'Return% 1Y',
    'Index',
    'EPS (ttm)',
    'Shs Outstand',
    'Perf Week',
    'Forward P/E',
    'Shs Float',
    'Short Float',
    'Perf Quarter',
    'Perf Half Y',
    'Book/sh',
    'Cash/sh',
    'P/C',
    'EPS next 5Y',
    '52W Range',
    'Dividend Est.',
    'Dividend TTM',
    'Quick Ratio',
    'Gross Margin',
    'ATR (14)',
    'Dividend Ex-Date',
    'Current Ratio',
    'EPS Y/Y TTM',
    'Oper. Margin',
    'RSI (14)',
    'Volatility',
    'Sales Y/Y TTM',
    'Profit Margin',
    'Target Price',
    'Option/Short',
    'LT Debt/Eq',
    'Payout',
    'Prev Close',
    'Sales Surprise',
    'SMA20',
    'SMA50',
    'SMA200',
]

PERFORMANCE_TABLE_ALL_FIELDS = [
    'Ticker',
    'Perf Week',
    'Perf Month',
    'Perf Quart',
    'Perf Half',
    'Perf Year',
    'Perf YTD',
    'Volatility W',
    'Volatility M',
    'Recom',
    'Avg Volume',
    'Rel Volume',
    'Price',
    'Change',
    'Volume',
    'Index',
    'P/E',
    'EPS (ttm)',
    'Insider Own',
    'Shs Outstand',
    'Market Cap',
    'Forward P/E',
    'EPS next Y',
    'Insider Trans',
    'Shs Float',
    'Income',
    'PEG',
    'EPS next Q',
    'Inst Own',
    'Short Float',
    'Perf Quarter',
    'Sales',
    'P/S',
    'EPS this Y',
    'Inst Trans',
    'Short Ratio',
    'Perf Half Y',
    'Book/sh',
    'P/B',
    'ROA',
    'Short Interest',
    'Cash/sh',
    'P/C',
    'EPS next 5Y',
    'ROE',
    '52W Range',
    'Dividend Est.',
    'P/FCF',
    'EPS past 5Y',
    'ROI',
    '52W High',
    'Beta',
    'Dividend TTM',
    'Quick Ratio',
    'Sales past 5Y',
    'Gross Margin',
    '52W Low',
    'ATR (14)',
    'Dividend Ex-Date',
    'Current Ratio',
    'EPS Y/Y TTM',
    'Oper. Margin',
    'RSI (14)',
    'Volatility',
    'Employees',
    'Debt/Eq',
    'Sales Y/Y TTM',
    'Profit Margin',
    'Target Price',
    'Option/Short',
    'LT Debt/Eq',
    'EPS Q/Q',
    'Payout',
    'Prev Close',
    'Sales Surprise',
    'EPS Surprise',
    'Sales Q/Q',
    'Earnings',
    'SMA20',
    'SMA50',
    'SMA200'
]

MONEY_COLUMNS = [
    'Avg Volume', 
    'Shs Outstand',
    'Market Cap',
    'Shs Float',
    'Income',
    'Sales',
    'Short Interest',
    'Outstanding',
    'Float'
]

PERCENTAJE_COLUMNS = [
    'Perf Week', 
    'Perf Month', 
    'Perf Quart', 
    'Perf Year', 
    'Perf YTD', 
    'Volatility W', 
    'Volatility M', 
    'Change', 
    'Insider Own',
    'EPS next Y',
    'Insider Trans',
    'Inst Own',
    'Perf Quarter',
    'EPS this Y',
    'Inst Trans',
    'Perf Half Y',
    'ROA',
    'EPS next 5Y',
    'ROE',
    'EPS past 5Y',
    'ROI',
    '52W High',
    'Sales past 5Y',
    'Gross Margin',
    '52W Low',
    'Sales Q/Q',
    'Oper. Margin',
    'EPS Q/Q',
    'Profit Margin',
    'Payout',
    'SMA20',
    'SMA50',
    'SMA200',
    'Dividend',
    'Payout Ratio',
    'EPS Surprise',
    'Revenue Surprise',
    'Float %',
    'Float Short',
    'Oper M',
    'Profit M',
    'Short Float',
    'EPS Y/Y TTM',
    'Sales Y/Y TTM',
    'Sales Surprise',
]

NUMERIC_COLUMNS = [
    'P/FCF',
    'Beta',
    'Quick Ratio',
    'ATR',
    'Employees',
    'Current Ratio',
    'RSI (14)',
    'Debt/Eq',
    'LT Debt/Eq',
    'Recom',
    'Rel Volume',
    'Price',
    'Volume',
    'P/E',
    'EPS (ttm)',
    'Forward P/E',
    'PEG',
    'P/S',
    'Book/sh',
    'P/B',
    'Target Price',
    'Cash/sh',
    'P/C',
    'EPS next Q',
    'Fwd P/E',
    'EPS',
    'Short Ratio',
    'Short Interest',
    'RSI',
    'Avg Volume',
    'Return% 1Y',
    'Shs Outstand',
    'Shs Float',
    'ATR (14)',
    'Prev Close',
]

BOOLEAN_COLUMNS = [
    'Optionable',
    'Shortable'
]

ALLOWED_INDUSTRIES = [
    "Advertising Agencies",
    "Aerospace & Defense",
    "Agricultural Inputs",
    "Airlines",
    "Airports & Air Services",
    "Aluminum",
    "Apparel Manufacturing",
    "Apparel Retail",
    "Asset Management",
    "Auto Manufacturers",
    "Auto Parts",
    "Auto & Truck Dealerships",
    "Banks - Diversified",
    "Banks - Regional",
    "Beverages - Brewers",
    "Beverages - Non-Alcoholic",
    "Beverages - Wineries & Distilleries",
    "Biotechnology",
    "Broadcasting",
    "Building Materials",
    "Building Products & Equipment",
    "Business Equipment & Supplies",
    "Capital Markets",
    "Chemicals",
    "Coking Coal",
    "Communication Equipment",
    "Computer Hardware",
    "Confectioners",
    "Conglomerates",
    "Consulting Services",
    "Consumer Electronics",
    "Copper",
    "Credit Services",
    "Department Stores",
    "Diagnostics & Research",
    "Discount Stores",
    "Drug Manufacturers - General",
    "Drug Manufacturers - Specialty & Generic",
    "Education & Training Services",
    "Electrical Equipment & Parts",
    "Electronic Components",
    "Electronic Gaming & Multimedia",
    "Electronics & Computer Distribution",
    "Engineering & Construction",
    "Entertainment",
    "Farm & Heavy Construction Machinery",
    "Farm Products",
    "Financial Conglomerates",
    "Financial Data & Stock Exchanges",
    "Food Distribution",
    "Footwear & Accessories",
    "Furnishings, Fixtures & Appliances",
    "Gambling",
    "Gold",
    "Grocery Stores",
    "Healthcare Plans",
    "Health Information Services",
    "Home Improvement Retail",
    "Household & Personal Products",
    "Industrial Distribution",
    "Information Technology Services",
    "Infrastructure Operations",
    "Insurance Brokers",
    "Insurance - Diversified",
    "Insurance - Life",
    "Insurance - Property & Casualty",
    "Insurance - Reinsurance",
    "Insurance - Specialty",
    "Integrated Freight & Logistics",
    "Internet Content & Information",
    "Internet Retail",
    "Leisure",
    "Lodging",
    "Lumber & Wood Production",
    "Luxury Goods",
    "Marine Shipping",
    "Medical Care Facilities",
    "Medical Devices",
    "Medical Distribution",
    "Medical Instruments & Supplies",
    "Metal Fabrication",
    "Mortgage Finance",
    "Oil & Gas Drilling",
    "Oil & Gas E&P",
    "Oil & Gas Equipment & Services",
    "Oil & Gas Integrated",
    "Oil & Gas Midstream",
    "Oil & Gas Refining & Marketing",
    "Other Industrial Metals & Mining",
    "Other Precious Metals & Mining",
    "Packaged Foods",
    "Packaging & Containers",
    "Paper & Paper Products",
    "Personal Services",
    "Pharmaceutical Retailers",
    "Pollution & Treatment Controls",
    "Publishing",
    "Railroads",
    "Real Estate - Development",
    "Real Estate - Diversified",
    "Real Estate Services",
    "Recreational Vehicles",
    "REIT - Diversified",
    "REIT - Healthcare Facilities",
    "REIT - Hotel & Motel",
    "REIT - Industrial",
    "REIT - Mortgage",
    "REIT - Office",
    "REIT - Residential",
    "REIT - Retail",
    "REIT - Specialty",
    "Rental & Leasing Services",
    "Residential Construction",
    "Resorts & Casinos",
    "Restaurants",
    "Scientific & Technical Instruments",
    "Security & Protection Services",
    "Semiconductor Equipment & Materials",
    "Semiconductors",
    "Shell Companies",
    "Silver",
    "Software - Application",
    "Software - Infrastructure",
    "Solar",
    "Specialty Business Services",
    "Specialty Chemicals",
    "Specialty Industrial Machinery",
    "Specialty Retail",
    "Staffing & Employment Services",
    "Steel",
    "Telecom Services",
    "Textile Manufacturing",
    "Thermal Coal",
    "Tobacco",
    "Tools & Accessories",
    "Travel Services",
    "Trucking",
    "Uranium",
    "Utilities - Diversified",
    "Utilities - Independent Power Producers",
    "Utilities - Regulated Electric",
    "Utilities - Regulated Gas",
    "Utilities - Regulated Water",
    "Utilities - Renewable",
    "Waste Management"
]