EARNINGS_CALENDAR_FOLDER = 'EarningsCalendars/AlphaVantage'
API_KEY = 'AR4WFMVZ4ODWUCH8'
POST_PROCESSED_COLUMNS = [
    'Ticker',
    'Company',
    'Sector',
    'Industry',
    'Country',
    'Market Cap',
    'P/E',
    'Fwd P/E',
    'PEG',
    'P/S',
    'P/B',
    'P/FCF',
    'EPS',
    'EPS next Q',
    'Sales',
    'Income',
    'Outstanding',
    'Float',
    'Short Ratio',
    'Short Interest',
    'LTDebt/Eq',
    'Debt/Eq',
    'Beta',
    'ATR',
    'RSI',
    'Earnings',
    'Employees',
    'Recom',
    'Avg Volume',
    'Rel Volume',
    'Volume',
    'Price',
    'Return% 1Y',
    'Index',
    'EPS (ttm)',
    'Shs Outstand',
    'Forward P/E',
    'Shs Float',
    'Book/sh',
    'Cash/sh',
    'P/C',
    '52W Range',
    'Dividend Est.',
    'Dividend TTM',
    'Quick Ratio',
    'ATR (14)',
    'Dividend Ex-Date',
    'Current Ratio',
    'RSI (14)',
    'Volatility',
    'Target Price',
    'Option/Short',
    'LT Debt/Eq',
    'Prev Close',
    'Perf Week (%)',
    'Perf Month (%)',
    'Perf Quart (%)',
    'Perf Year (%)',
    'Perf YTD (%)',
    'Volatility M (%)',
    'Change (%)',
    'Insider Own (%)',
    'EPS next Y (%)',
    'Insider Trans (%)',
    'Inst Own (%)',
    'Perf Quarter (%)',
    'EPS this Y (%)',
    'Inst Trans (%)',
    'Perf Half Y (%)',
    'ROA (%)',
    'EPS next 5Y (%)',
    'ROE (%)',
    'EPS past 5Y (%)',
    'ROI (%)',
    '52W High (%)',
    'Sales past 5Y (%)',
    'Gross Margin (%)',
    '52W Low (%)',
    'Sales Q/Q (%)',
    'Oper. Margin (%)',
    'EPS Q/Q (%)',
    'Profit Margin (%)',
    'Payout (%)',
    'SMA20 (%)',
    'SMA50 (%)',
    'SMA200 (%)',
    'Dividend (%)',
    'Payout Ratio (%)',
    'EPS Surprise (%)',
    'Revenue Surprise (%)',
    'Float % (%)',
    'Float Short (%)',
    'Oper M (%)',
    'Profit M (%)',
    'Short Float (%)',
    'EPS Y/Y TTM (%)',
    'Sales Y/Y TTM (%)',
    'Sales Surprise (%)',
    '52W Low',
    '52W High',
    'Earnings Time'
]
INCLUDE_COLUMNS = [
    'Ticker',
    'Market Cap',
    'Price',
    'P/E',
    'P/S',
    'Book/sh',
    'EPS (ttm)',
    'EPS next Q',
    'Perf Week (%)',
    'Perf Month (%)',
    'Sales',
    'ROI (%)',
    'Beta',
    'Short Interest',
    'Volatility',
    'Volatility W (%)',
    'Volatility M (%)',
    'Volume',
    'Rel Volume',
    'Avg Volume',
    '52W Low',
    '52W High',
    'Earnings Time',
]

DATA_FOLDER = '/Users/administrador/Documents/DataScience/Projects/Finviz/_Data'
FINVIZ_DATA_CALENDAR_FOLDER = '/FinvizDataCalendars'
FINVIZ_RAW_DATA_FOLDER = '/FinvizRawData'
# Example: (1, 3)  One day before, Three days after
DEFAULT_BEFORE_EARNINGS_DATE_DAYS=1
DEFAULT_AFTER_EARNINGS_DATE_DAYS=5
# Default ranges to calculate pct and diff (days_before, days_after)
RANGES = [(1, 0), (1, 2), (1, 3), (1, 5), (1, 8), (1, 13), (1, 21)]


ALL_STOCK_INDUSTRIES = [
    "Exchange Traded Fund",
    "Advertising Agencies",
    "Aerospace & Defense",
    "Agricultural Inputs",
    "Airlines",
    "Airports & Air Services",
    "Aluminum",
    "Apparel Manufacturing",
    "Apparel Retail",
    "Asset Management",
    "Auto Manufacturers",
    "Auto Parts",
    "Auto & Truck Dealerships",
    "Banks - Diversified",
    "Banks - Regional",
    "Beverages - Brewers",
    "Beverages - Non-Alcoholic",
    "Beverages - Wineries & Distilleries",
    "Biotechnology",
    "Broadcasting",
    "Building Materials",
    "Building Products & Equipment",
    "Business Equipment & Supplies",
    "Capital Markets",
    "Chemicals",
    "Coking Coal",
    "Communication Equipment",
    "Computer Hardware",
    "Confectioners",
    "Conglomerates",
    "Consulting Services",
    "Consumer Electronics",
    "Copper",
    "Credit Services",
    "Department Stores",
    "Diagnostics & Research",
    "Discount Stores",
    "Drug Manufacturers - General",
    "Drug Manufacturers - Specialty & Generic",
    "Education & Training Services",
    "Electrical Equipment & Parts",
    "Electronic Components",
    "Electronic Gaming & Multimedia",
    "Electronics & Computer Distribution",
    "Engineering & Construction",
    "Entertainment",
    "Farm & Heavy Construction Machinery",
    "Farm Products",
    "Financial Conglomerates",
    "Financial Data & Stock Exchanges",
    "Food Distribution",
    "Footwear & Accessories",
    "Furnishings, Fixtures & Appliances",
    "Gambling",
    "Gold",
    "Grocery Stores",
    "Healthcare Plans",
    "Health Information Services",
    "Home Improvement Retail",
    "Household & Personal Products",
    "Industrial Distribution",
    "Information Technology Services",
    "Infrastructure Operations",
    "Insurance Brokers",
    "Insurance - Diversified",
    "Insurance - Life",
    "Insurance - Property & Casualty",
    "Insurance - Reinsurance",
    "Insurance - Specialty",
    "Integrated Freight & Logistics",
    "Internet Content & Information",
    "Internet Retail",
    "Leisure",
    "Lodging",
    "Lumber & Wood Production",
    "Luxury Goods",
    "Marine Shipping",
    "Medical Care Facilities",
    "Medical Devices",
    "Medical Distribution",
    "Medical Instruments & Supplies",
    "Metal Fabrication",
    "Mortgage Finance",
    "Oil & Gas Drilling",
    "Oil & Gas E&P",
    "Oil & Gas Equipment & Services",
    "Oil & Gas Integrated",
    "Oil & Gas Midstream",
    "Oil & Gas Refining & Marketing",
    "Other Industrial Metals & Mining",
    "Other Precious Metals & Mining",
    "Packaged Foods",
    "Packaging & Containers",
    "Paper & Paper Products",
    "Personal Services",
    "Pharmaceutical Retailers",
    "Pollution & Treatment Controls",
    "Publishing",
    "Railroads",
    "Real Estate - Development",
    "Real Estate - Diversified",
    "Real Estate Services",
    "Recreational Vehicles",
    "REIT - Diversified",
    "REIT - Healthcare Facilities",
    "REIT - Hotel & Motel",
    "REIT - Industrial",
    "REIT - Mortgage",
    "REIT - Office",
    "REIT - Residential",
    "REIT - Retail",
    "REIT - Specialty",
    "Rental & Leasing Services",
    "Residential Construction",
    "Resorts & Casinos",
    "Restaurants",
    "Scientific & Technical Instruments",
    "Security & Protection Services",
    "Semiconductor Equipment & Materials",
    "Semiconductors",
    "Shell Companies",
    "Silver",
    "Software - Application",
    "Software - Infrastructure",
    "Solar",
    "Specialty Business Services",
    "Specialty Chemicals",
    "Specialty Industrial Machinery",
    "Specialty Retail",
    "Staffing & Employment Services",
    "Steel",
    "Telecom Services",
    "Textile Manufacturing",
    "Thermal Coal",
    "Tobacco",
    "Tools & Accessories",
    "Travel Services",
    "Trucking",
    "Uranium",
    "Utilities - Diversified",
    "Utilities - Independent Power Producers",
    "Utilities - Regulated Electric",
    "Utilities - Regulated Gas",
    "Utilities - Regulated Water",
    "Utilities - Renewable",
    "Waste Management"
]

TRACKED_INDUSTRIES = [
    'Gold',
    'Internet Retail',
    'Tobacco',
    'Telecom Services',
    'Credit Services',
    'Department Stores', 
    'Computer Hardware',
    'Mortgage Finance',
    'Biotechnology',
    'Capital Markets',
    # 'Restaurants'

]

TRACKED_REITS = [
    "REIT - Diversified",
    "REIT - Healthcare Facilities",
    "REIT - Hotel & Motel",
    "REIT - Industrial",
    "REIT - Mortgage",
    "REIT - Office",
    "REIT - Residential",
    "REIT - Retail",
    "REIT - Specialty"
]

TRACKED_OIL = [
    "Oil & Gas Drilling",
    "Oil & Gas E&P",
    "Oil & Gas Equipment & Services",
    "Oil & Gas Integrated",
    "Oil & Gas Midstream",
    "Oil & Gas Refining & Marketing",
]

TRACKED_FINANCIAL = [
    "Banks - Diversified",
    "Banks - Regional",
    "Capital Markets",
    "Credit Services",
    "Financial Conglomerates",
    "Insurance Brokers",
    "Insurance - Diversified",
    "Insurance - Life",
    "Insurance - Property & Casualty",
    "Insurance - Reinsurance",
    "Insurance - Specialty",
    "Mortgage Finance"
]

TRACKED_TECH = [
    "Software - Application",
    "Software - Infrastructure",
    "Information Technology Services",
    "Biotechnology",
    "Computer Hardware",
    "Engineering & Construction",
]